import './globals.css'
import { AppProps } from 'next/app';

export const metadata = {
  title: 'Watch Next!',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className="bg-background text-text font-primary">
        {children}
      </body>
    </html>
  )
}
